// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Grade struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Score    int    `json:"score"`
	Comment  string `json:"comment"`
	Finished string `json:"finished"`
}

type ListReq struct {
	Limit    int    `json:"limit" form:"limit"`
	Classify string `json:"classify" form:"classify"`
}

type ListResp struct {
	GradeList []Grade `json:"grade_list"`
}

type SubmitReq struct {
	Name    string `json:"name" form:"name"`
	Score   int    `json:"score" form:"score"`
	Comment string `json:"comment" form:"comment"`
}

type SubmitResp struct {
}
