// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gradeFieldNames          = builder.RawFieldNames(&Grade{})
	gradeRows                = strings.Join(gradeFieldNames, ",")
	gradeRowsExpectAutoSet   = strings.Join(stringx.Remove(gradeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gradeRowsWithPlaceHolder = strings.Join(stringx.Remove(gradeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gradeModel interface {
		Insert(ctx context.Context, data *Grade) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Grade, error)
		Update(ctx context.Context, data *Grade) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGradeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Grade struct {
		Id        int64          `db:"id"`         // 主键ID
		Name      string         `db:"name"`       // 玩家名称
		Score     int64          `db:"score"`      // 游戏分数
		Comment   sql.NullString `db:"comment"`    // 玩家评论
		Finished  time.Time      `db:"finished"`   // 完成时间
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
	}
)

func newGradeModel(conn sqlx.SqlConn) *defaultGradeModel {
	return &defaultGradeModel{
		conn:  conn,
		table: "`grade`",
	}
}

func (m *defaultGradeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGradeModel) FindOne(ctx context.Context, id int64) (*Grade, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gradeRows, m.table)
	var resp Grade
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGradeModel) Insert(ctx context.Context, data *Grade) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, gradeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Score, data.Comment, data.Finished)
	return ret, err
}

func (m *defaultGradeModel) Update(ctx context.Context, data *Grade) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gradeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Score, data.Comment, data.Finished, data.Id)
	return err
}

func (m *defaultGradeModel) tableName() string {
	return m.table
}
